---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp admin.php $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp htaccess $DEPLOYPATH/.htaccess
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R PHPMailer $DEPLOYPATH
